name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

  workflow_dispatch:
    inputs:
      run_tests:
        description: "Run AI generated tests?"
        required: true
        default: "true"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install Python Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run AI Test Generator
        run: |
          python python/app.py

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Backend Dependencies
        run: |
          cd Backend
          npm install

      - name: Start Backend
        run: |
          cd Backend
          npm start
