name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

  workflow_dispatch:
    inputs:
      run_tests:
        description: "Run AI generated tests?"
        required: true
        default: "true"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install Python Dependencies
        run: pip install -r requirements.txt

      - name: Run AI Tester
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python Intelligence-Module/Orchestrator.py TARGET_CODE/target.py

      - name: Build Successful Message
        if: success()
        run: echo "Build Successful"